name: sync submodule gitlab

on: [push]

jobs:
  build:
    name: sync submodule gitlab
    runs-on: self-hosted
    steps:
    - name: Clone a remote repo
      env:
        DEPLOY_KEY: ${{ secrets.NEXTFLOW_CI_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        echo $GITHUB_HEAD_REF
        echo $GITHUB_REF
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git clone git@gitlab.internal.sanger.ac.uk:hgi-projects/nextflow_ci.git
        cd nextflow_ci
        ls -ltra . 
