name: sync submodule gitlab

on: [push]

jobs:
  build:
    name: sync submodule gitlab
    runs-on: self-hosted
    steps:
    - name: Clone a remote repo
      env:
        DEPLOY_KEY: ${{ secrets.NEXTFLOW_CI_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        rm -rf nextflow_ci
        git clone git@gitlab.internal.sanger.ac.uk:hgi-projects/nextflow_ci.git
        cd nextflow_ci
        ls -ltra . 
        git branch -a
        echo branch is $GITHUB_REF
        git show-ref --verify --quiet $GITHUB_REF && echo branch exists 
        git config --get remote.origin.url
        git pull --recurse-submodules
        git submodule update --remote --recursive
        git submodule update --init --recursive --remote
        git add nextflow_ci && git commit -m "add submodule" && git push -u origin
